
export const ADD_BOOK_LIST = "ADD_BOOK_LIST"
export const FILTER_BOOK_LIST = "FILTER_BOOK_LIST"
export const ADD_BOOK_CATEGORIES = "ADD_BOOK_CATEGORIES"
export const DELETE_BOOK = "DELETE_BOOK"


export const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST"